import Dexie, { type EntityTable } from 'dexie'
import type { Client, Invoice, Product, LaborRate, StoreSettings } from '@/types'

class DecoratorDB extends Dexie {
  clients!: EntityTable<Client, 'id'>
  invoices!: EntityTable<Invoice, 'id'>
  products!: EntityTable<Product, 'id'>
  laborRates!: EntityTable<LaborRate, 'id'>
  settings!: EntityTable<StoreSettings, 'id'>

  constructor() {
    super('DecoratorDB')
    this.version(1).stores({
      clients: '++id, name, phone, createdAt',
      invoices: '++id, number, date, clientName, status, createdAt',
      products: '++id, name, category',
      laborRates: '++id, name',
      settings: '++id',
    })
    // v2 — пустая миграция (схема не менялась). Раньше здесь был
    // tx.table('products').clear(), который при апгрейде стирал каталог,
    // включая товары, добавленные пользователем. Убрано во избежание потери данных.
    this.version(2).stores({
      clients: '++id, name, phone, createdAt',
      invoices: '++id, number, date, clientName, status, createdAt',
      products: '++id, name, category',
      laborRates: '++id, name',
      settings: '++id',
    })
  }
}

export const db = new DecoratorDB()

const CATALOG_PRODUCTS: Omit<Product, 'id'>[] = [
        { name: 'KIITOS FLEXPOOL', unit: '14 кг', price: 5703.46, coverage: 0, category: 'KIITOS', description: 'Готовая гидроизоляционная мастика для влажных помещений (санузлы, ванные, бассейны)' },
        { name: 'KIITOS FLEXPOOL', unit: '7 кг', price: 2980.47, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS FLEXPOOL PRIMER', unit: '1 л', price: 338.58, coverage: 0, category: 'KIITOS', description: 'Водорастворимый грунт для улучшения адгезии гидроизоляционных мастик' },
        { name: 'KIITOS F-TAPE', unit: '1 рул.', price: 660.0, coverage: 0, category: 'KIITOS', description: 'Армирующая лента для углов, 0,2 м × 25 м' },
        { name: 'KIITOS HYDROFLEX PU', unit: '7 кг', price: 5702.52, coverage: 0, category: 'KIITOS', description: 'Однокомп. ПУ-мастика (кровля, балконы, террасы, фундаменты). Срок 25+ лет.' },
        { name: 'KIITOS HYDROFLEX PU', unit: '15 кг', price: 12133.56, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS HYDROFLEX PU', unit: '25 кг', price: 20172.36, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS PU PRIMER R', unit: '5 кг', price: 3851.93, coverage: 0, category: 'KIITOS', description: 'Однокомп. ПУ-грунт-праймер для наружных работ, сухой остаток 50%' },
        { name: 'KIITOS PU 40', unit: '0,6 кг', price: 753.64, coverage: 0, category: 'KIITOS', description: 'Универсальный низкомодульный ПУ-герметик' },
        { name: 'KIITOS WATERGUM PRIMER', unit: '1 л', price: 285.54, coverage: 0, category: 'KIITOS', description: 'Грунт-концентрат 1:6 (при 1:3–1:4 — влагоизолятор)' },
        { name: 'KIITOS WATERGUM PRIMER', unit: '3 л', price: 765.36, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS WATERGUM PRIMER', unit: '10 л', price: 2072.5, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS AQUA PRIMER', unit: '1 л', price: 150.73, coverage: 0, category: 'KIITOS', description: 'Готовый грунт глубокого проникновения' },
        { name: 'KIITOS AQUA PRIMER', unit: '5 л', price: 502.43, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS AQUA PRIMER', unit: '10 л', price: 728.52, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS MASTER', unit: '10 л', price: 1673.84, coverage: 0, category: 'KIITOS', description: 'Клей повышенной влагостойкости и прочности. Для тяжёлых обоев, флизелина, стеклообоев, текстиля' },
        { name: 'KIITOS MASTER', unit: '5 л', price: 955.99, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS TAPETTI', unit: '10 л', price: 1348.17, coverage: 0, category: 'KIITOS', description: 'Универсальный клей для всех видов обоев под окраску' },
        { name: 'KIITOS TAPETTI', unit: '5 л', price: 762.01, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'STEP', unit: '1,3 кг', price: 410.55, coverage: 0, category: 'KIITOS', description: 'Дисперсионный акриловый клей для ПВХ-линолеума, ковровых покрытий' },
        { name: 'STEP', unit: '3 кг', price: 970.28, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'STEP', unit: '15 кг', price: 4140.28, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'STEP PLUS', unit: '2,5 кг', price: 1482.86, coverage: 0, category: 'KIITOS', description: 'Высококач. клей для LVT, кварц-винила, текстиля, ковролина, коммерческого ПВХ' },
        { name: 'STEP PLUS', unit: '6,5 кг', price: 3063.85, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'STEP PLUS', unit: '13 кг', price: 5675.67, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'FIX-ALL', unit: '6 кг', price: 3259.78, coverage: 0, category: 'KIITOS', description: 'Клей-фиксатор для ковровой плитки, ПВХ и виниловых покрытий, LVT' },
        { name: 'FIX-ALL', unit: '12 кг', price: 6249.78, coverage: 0, category: 'KIITOS', description: '' },
        { name: '2K ELASTIC', unit: '7,2 кг (A+B)', price: 3933.99, coverage: 0, category: 'KIITOS', description: 'Двухкомп. ПУ-клей для спортивных покрытий (резина, ПВХ, стеклопластик)' },
        { name: 'GREEN LINE', unit: '10 кг (A+B)', price: 4094.76, coverage: 0, category: 'KIITOS', description: 'Двухкомп. ПУ-клей для искусственной травы, цвет зелёный' },
        { name: 'KIITOS 2K PU ECO', unit: '5,5 кг (A+B)', price: 1788.0, coverage: 0, category: 'KIITOS', description: 'Двухкомп. ПУ-клей для паркета, без растворителей' },
        { name: 'KIITOS 2K PU STRONG', unit: '5,4 кг (A+B)', price: 1917.0, coverage: 0, category: 'KIITOS', description: 'Двухкомп. ПУ-клей с усиленным клеевым швом, для экзотики' },
        { name: 'KIITOS 2K LINE', unit: '5,84 кг (A+B)', price: 2266.2, coverage: 0, category: 'KIITOS', description: 'Двухкомп. ПУ-клей для паркета, DIY формат' },
        { name: 'KIITOS MS SILEX', unit: '14 кг (2×7)', price: 8250.0, coverage: 0, category: 'KIITOS', description: 'Однокомп. клей на МС-полимере для всех видов паркета' },
        { name: 'KIITOS PU PRIMER', unit: '5 кг', price: 5007.5, coverage: 0, category: 'KIITOS', description: 'Однокомп. ПУ-грунт, сухой остаток 100%, без растворителей' },
        { name: 'KIITOS PU PRIMER R', unit: '5 кг', price: 3826.8, coverage: 0, category: 'KIITOS', description: 'Однокомп. ПУ-грунт, сухой остаток 50%, с растворителем' },
        { name: 'KIITOS PRIMER X', unit: '4,5 кг (A+B)', price: 7611.74, coverage: 0, category: 'KIITOS', description: 'Двухкомп. эпоксидный грунт-праймер' },
        { name: 'KIITOS D2P PVA', unit: '0,5 л', price: 264.61, coverage: 0, category: 'KIITOS', description: 'Профессиональный столярный клей, класс D2' },
        { name: 'KIITOS D2P PVA', unit: '1 л', price: 393.57, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS D3P PVA', unit: '0,5 л', price: 326.58, coverage: 0, category: 'KIITOS', description: 'Влагостойкий столярный клей, класс D3 (DIN EN 204)' },
        { name: 'KIITOS D3P PVA', unit: '1 л', price: 522.52, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS D3P PVA', unit: '30 л', price: 9922.0, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS D4P PUR', unit: '0,5 л', price: 616.31, coverage: 0, category: 'KIITOS', description: 'Однокомп. ПУ-клей для дерева, 100% сухой остаток' },
        { name: 'KIITOS Затирка №10', unit: '1 кг', price: 195.0, coverage: 0, category: 'KIITOS', description: 'Белый' },
        { name: 'KIITOS Затирка №11', unit: '1 кг', price: 195.0, coverage: 0, category: 'KIITOS', description: 'Жасмин' },
        { name: 'KIITOS Затирка №21', unit: '1 кг', price: 195.0, coverage: 0, category: 'KIITOS', description: 'Карамель' },
        { name: 'KIITOS Затирка №25', unit: '1 кг', price: 195.0, coverage: 0, category: 'KIITOS', description: 'Багамы' },
        { name: 'KIITOS Затирка №29', unit: '1 кг', price: 195.0, coverage: 0, category: 'KIITOS', description: 'Светло-бежевый' },
        { name: 'KIITOS Затирка №30', unit: '1 кг', price: 195.0, coverage: 0, category: 'KIITOS', description: 'Бежевый' },
        { name: 'KIITOS Затирка №31', unit: '1 кг', price: 195.0, coverage: 0, category: 'KIITOS', description: 'Коричневый' },
        { name: 'KIITOS Затирка №32', unit: '1 кг', price: 195.0, coverage: 0, category: 'KIITOS', description: 'Тёмно-коричневый' },
        { name: 'KIITOS Затирка №40', unit: '1 кг', price: 195.0, coverage: 0, category: 'KIITOS', description: 'Стальной серый' },
        { name: 'KIITOS Затирка №41', unit: '1 кг', price: 195.0, coverage: 0, category: 'KIITOS', description: 'Жемчужно-серый' },
        { name: 'KIITOS Затирка №43', unit: '1 кг', price: 195.0, coverage: 0, category: 'KIITOS', description: 'Светло-серый' },
        { name: 'KIITOS Затирка №44', unit: '1 кг', price: 195.0, coverage: 0, category: 'KIITOS', description: 'Серый' },
        { name: 'KIITOS Затирка №45', unit: '1 кг', price: 195.0, coverage: 0, category: 'KIITOS', description: 'Антрацит' },
        { name: 'KIITOS Затирка №48', unit: '1 кг', price: 195.0, coverage: 0, category: 'KIITOS', description: 'Мокрый асфальт' },
        { name: 'KIITOS Затирка №50', unit: '1 кг', price: 202.65, coverage: 0, category: 'KIITOS', description: 'Чёрный' },
        { name: 'Cement Remover', unit: '0,5 л', price: 184.0, coverage: 0, category: 'KIITOS', description: 'Удалитель остатков затирки и цемента (спрей)' },
        { name: 'Cement Remover', unit: '0,5 л', price: 209.0, coverage: 0, category: 'KIITOS', description: 'Удалитель остатков затирки (концентрат)' },
        { name: 'KIITOS COLORIST', unit: '0,9 кг', price: 526.21, coverage: 0, category: 'KIITOS', description: 'Белый' },
        { name: 'KIITOS COLORIST', unit: '2,7 кг', price: 1388.57, coverage: 0, category: 'KIITOS', description: 'Белый' },
        { name: 'KIITOS COLORIST', unit: '10 кг', price: 5388.37, coverage: 0, category: 'KIITOS', description: 'Белый' },
        { name: 'KIITOS COLORIST', unit: '0,9 кг', price: 442.08, coverage: 0, category: 'KIITOS', description: 'Зелёный' },
        { name: 'KIITOS COLORIST', unit: '2,7 кг', price: 1161.42, coverage: 0, category: 'KIITOS', description: 'Зелёный' },
        { name: 'KIITOS COLORIST', unit: '10 кг', price: 4453.58, coverage: 0, category: 'KIITOS', description: 'Зелёный' },
        { name: 'KIITOS COLORIST', unit: '0,9 кг', price: 425.0, coverage: 0, category: 'KIITOS', description: 'Серый' },
        { name: 'KIITOS COLORIST', unit: '2,7 кг', price: 1115.3, coverage: 0, category: 'KIITOS', description: 'Серый' },
        { name: 'KIITOS COLORIST', unit: '10 кг', price: 4263.78, coverage: 0, category: 'KIITOS', description: 'Серый' },
        { name: 'KIITOS COLORIST', unit: '0,9 кг', price: 389.12, coverage: 0, category: 'KIITOS', description: 'Красно-коричневый' },
        { name: 'KIITOS COLORIST', unit: '2,7 кг', price: 1018.41, coverage: 0, category: 'KIITOS', description: 'Красно-коричневый' },
        { name: 'KIITOS COLORIST', unit: '10 кг', price: 3865.07, coverage: 0, category: 'KIITOS', description: 'Красно-коричневый' },
        { name: 'KIITOS COLORIST', unit: '25 кг', price: 7801.74, coverage: 0, category: 'KIITOS', description: 'Красно-коричневый' },
        { name: 'KIITOS COLORIST', unit: '0,9 кг', price: 446.5, coverage: 0, category: 'KIITOS', description: 'Светло-серый' },
        { name: 'KIITOS COLORIST', unit: '2,7 кг', price: 1199.2, coverage: 0, category: 'KIITOS', description: 'Светло-серый' },
        { name: 'KIITOS COLORIST', unit: '10 кг', price: 4213.51, coverage: 0, category: 'KIITOS', description: 'Светло-серый' },
        { name: 'KIITOS COLORIST', unit: '0,9 кг', price: 384.35, coverage: 0, category: 'KIITOS', description: 'Чёрный' },
        { name: 'KIITOS COLORIST', unit: '2,7 кг', price: 1005.54, coverage: 0, category: 'KIITOS', description: 'Чёрный' },
        { name: 'KIITOS COLORIST', unit: '10 кг', price: 3812.09, coverage: 0, category: 'KIITOS', description: 'Чёрный' },
        { name: 'KIITOS COLORIST', unit: '0,9 кг', price: 436.14, coverage: 0, category: 'KIITOS', description: 'Коричневый/шоколад' },
        { name: 'KIITOS COLORIST', unit: '2,7 кг', price: 1145.37, coverage: 0, category: 'KIITOS', description: 'Коричневый/шоколад' },
        { name: 'KIITOS COLORIST', unit: '10 кг', price: 4387.53, coverage: 0, category: 'KIITOS', description: 'Коричневый/шоколад' },
        { name: 'KIITOS SPECIALIST', unit: '3 кг', price: 422.54, coverage: 0, category: 'KIITOS', description: 'Матовая (базовая)' },
        { name: 'KIITOS SPECIALIST', unit: '7 кг', price: 842.73, coverage: 0, category: 'KIITOS', description: 'Матовая' },
        { name: 'KIITOS SPECIALIST', unit: '14 кг', price: 1511.08, coverage: 0, category: 'KIITOS', description: 'Матовая' },
        { name: 'KIITOS SPECIALIST', unit: '25 кг', price: 2518.43, coverage: 0, category: 'KIITOS', description: 'Матовая' },
        { name: 'KIITOS SPECIALIST', unit: '3 кг', price: 494.73, coverage: 0, category: 'KIITOS', description: 'Влагостойкая матовая' },
        { name: 'KIITOS SPECIALIST', unit: '7 кг', price: 1028.77, coverage: 0, category: 'KIITOS', description: 'Влагостойкая матовая' },
        { name: 'KIITOS SPECIALIST', unit: '14 кг', price: 1903.99, coverage: 0, category: 'KIITOS', description: 'Влагостойкая матовая' },
        { name: 'KIITOS SPECIALIST', unit: '25 кг', price: 3027.15, coverage: 0, category: 'KIITOS', description: 'Влагостойкая матовая' },
        { name: 'KIITOS SPECIALIST', unit: '3 кг', price: 577.47, coverage: 0, category: 'KIITOS', description: 'Моющаяся матовая' },
        { name: 'KIITOS SPECIALIST', unit: '7 кг', price: 1225.22, coverage: 0, category: 'KIITOS', description: 'Моющаяся матовая' },
        { name: 'KIITOS SPECIALIST', unit: '14 кг', price: 2338.24, coverage: 0, category: 'KIITOS', description: 'Моющаяся матовая' },
        { name: 'KIITOS SPECIALIST', unit: '25 кг', price: 3654.0, coverage: 0, category: 'KIITOS', description: 'Моющаяся матовая' },
        { name: 'KIITOS INTERIO', unit: '1,5 кг', price: 366.98, coverage: 0, category: 'KIITOS', description: 'Интерьерная (база A)' },
        { name: 'KIITOS INTERIO', unit: '3,8 кг', price: 809.55, coverage: 0, category: 'KIITOS', description: 'Интерьерная (база A)' },
        { name: 'KIITOS INTERIO', unit: '7,2 кг', price: 1293.08, coverage: 0, category: 'KIITOS', description: 'Интерьерная (база A)' },
        { name: 'KIITOS INTERIO', unit: '14 кг', price: 2181.38, coverage: 0, category: 'KIITOS', description: 'Интерьерная (база A)' },
        { name: 'KIITOS INTERIO', unit: '1,5 кг', price: 409.5, coverage: 0, category: 'KIITOS', description: 'Влагостойкая (база A)' },
        { name: 'KIITOS INTERIO', unit: '3,8 кг', price: 911.93, coverage: 0, category: 'KIITOS', description: 'Влагостойкая (база A)' },
        { name: 'KIITOS INTERIO', unit: '7,2 кг', price: 1460.03, coverage: 0, category: 'KIITOS', description: 'Влагостойкая (база A)' },
        { name: 'KIITOS INTERIO', unit: '14 кг', price: 2472.75, coverage: 0, category: 'KIITOS', description: 'Влагостойкая (база A)' },
        { name: 'KIITOS INTERIO', unit: '1,5 кг', price: 480.38, coverage: 0, category: 'KIITOS', description: 'Моющаяся (база A)' },
        { name: 'KIITOS INTERIO', unit: '3,8 кг', price: 1089.9, coverage: 0, category: 'KIITOS', description: 'Моющаяся (база A)' },
        { name: 'KIITOS INTERIO', unit: '7,2 кг', price: 1754.55, coverage: 0, category: 'KIITOS', description: 'Моющаяся (база A)' },
        { name: 'KIITOS INTERIO', unit: '14 кг', price: 2981.48, coverage: 0, category: 'KIITOS', description: 'Моющаяся (база A)' },
        { name: 'KIITOS INTERIO', unit: '1,2 кг', price: 437.85, coverage: 0, category: 'KIITOS', description: 'Моющаяся (база C, насыщ. тона)' },
        { name: 'KIITOS INTERIO', unit: '3 кг', price: 987.53, coverage: 0, category: 'KIITOS', description: 'Моющаяся (база C)' },
        { name: 'KIITOS INTERIO', unit: '6,3 кг', price: 1587.6, coverage: 0, category: 'KIITOS', description: 'Моющаяся (база C)' },
        { name: 'KIITOS INTERIO', unit: '13 кг', price: 2690.1, coverage: 0, category: 'KIITOS', description: 'Моющаяся (база C)' },
        { name: 'KIITOS INTERIO', unit: '1,5 кг', price: 573.3, coverage: 0, category: 'KIITOS', description: 'Износостойкая (база A)' },
        { name: 'KIITOS INTERIO', unit: '3,8 кг', price: 1321.43, coverage: 0, category: 'KIITOS', description: 'Износостойкая (база A)' },
        { name: 'KIITOS INTERIO', unit: '7,2 кг', price: 2137.28, coverage: 0, category: 'KIITOS', description: 'Износостойкая (база A)' },
        { name: 'KIITOS INTERIO', unit: '14 кг', price: 3642.98, coverage: 0, category: 'KIITOS', description: 'Износостойкая (база A)' },
        { name: 'KIITOS INTERIO', unit: '1,2 кг', price: 522.9, coverage: 0, category: 'KIITOS', description: 'Износостойкая (база C)' },
        { name: 'KIITOS INTERIO', unit: '3 кг', price: 1197.0, coverage: 0, category: 'KIITOS', description: 'Износостойкая (база C)' },
        { name: 'KIITOS INTERIO', unit: '6,3 кг', price: 1932.53, coverage: 0, category: 'KIITOS', description: 'Износостойкая (база C)' },
        { name: 'KIITOS INTERIO', unit: '13 кг', price: 3285.45, coverage: 0, category: 'KIITOS', description: 'Износостойкая (база C)' },
        { name: 'KIITOS INTERIO', unit: '1,2 кг', price: 623.7, coverage: 0, category: 'KIITOS', description: 'Особо прочная (база A)' },
        { name: 'KIITOS INTERIO', unit: '3 кг', price: 1447.43, coverage: 0, category: 'KIITOS', description: 'Особо прочная (база A)' },
        { name: 'KIITOS INTERIO', unit: '6,3 кг', price: 2345.18, coverage: 0, category: 'KIITOS', description: 'Особо прочная (база A)' },
        { name: 'KIITOS INTERIO', unit: '13 кг', price: 4000.5, coverage: 0, category: 'KIITOS', description: 'Особо прочная (база A)' },
        { name: 'KIITOS INTERIO', unit: '1,2 кг', price: 513.45, coverage: 0, category: 'KIITOS', description: 'Особо прочная (база C)' },
        { name: 'KIITOS INTERIO', unit: '3 кг', price: 1171.8, coverage: 0, category: 'KIITOS', description: 'Особо прочная (база C)' },
        { name: 'KIITOS INTERIO', unit: '6,3 кг', price: 1891.58, coverage: 0, category: 'KIITOS', description: 'Особо прочная (база C)' },
        { name: 'KIITOS INTERIO', unit: '13 кг', price: 3214.58, coverage: 0, category: 'KIITOS', description: 'Особо прочная (база C)' },
        { name: 'KIITOS MINERAL EXPERT', unit: '1,5 кг', price: 521.33, coverage: 0, category: 'KIITOS', description: 'Матовая (база A)' },
        { name: 'KIITOS MINERAL EXPERT', unit: '3,8 кг', price: 1192.28, coverage: 0, category: 'KIITOS', description: '(база A)' },
        { name: 'KIITOS MINERAL EXPERT', unit: '7,2 кг', price: 1923.08, coverage: 0, category: 'KIITOS', description: '(база A)' },
        { name: 'KIITOS MINERAL EXPERT', unit: '14 кг', price: 3272.85, coverage: 0, category: 'KIITOS', description: '(база A)' },
        { name: 'KIITOS MINERAL EXPERT', unit: '1,2 кг', price: 492.98, coverage: 0, category: 'KIITOS', description: '(база C)' },
        { name: 'KIITOS MINERAL EXPERT', unit: '3 кг', price: 1124.55, coverage: 0, category: 'KIITOS', description: '(база C)' },
        { name: 'KIITOS MINERAL EXPERT', unit: '6,3 кг', price: 1814.4, coverage: 0, category: 'KIITOS', description: '(база C)' },
        { name: 'KIITOS MINERAL EXPERT', unit: '13 кг', price: 3083.85, coverage: 0, category: 'KIITOS', description: '(база C)' },
        { name: 'KIITOS FRESH WOOD', unit: '1,2 кг', price: 781.2, coverage: 0, category: 'KIITOS', description: 'Полуматовая, для каркасного домостроения, фасады (база A)' },
        { name: 'KIITOS FRESH WOOD (база A)', unit: '3 кг', price: 1630.13, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS FRESH WOOD (база A)', unit: '6 кг', price: 2929.5, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS FRESH WOOD (база A)', unit: '13 кг', price: 5095.13, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS FRESH WOOD (база C)', unit: '1 кг', price: 639.45, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS FRESH WOOD (база C)', unit: '2,6 кг', price: 1318.28, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS FRESH WOOD (база C)', unit: '5,5 кг', price: 2357.78, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS FRESH WOOD (база C)', unit: '12 кг', price: 4090.28, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS COUNTRY WOOD (база A)', unit: '1,2 кг', price: 1083.6, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS COUNTRY WOOD (база A)', unit: '3 кг', price: 2290.05, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS COUNTRY WOOD (база A)', unit: '6 кг', price: 4140.68, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS COUNTRY WOOD (база A)', unit: '13 кг', price: 7222.95, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS COUNTRY WOOD (база C)', unit: '1 кг', price: 982.8, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS COUNTRY WOOD (база C)', unit: '2,6 кг', price: 2069.55, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS COUNTRY WOOD (база C)', unit: '5,5 кг', price: 3734.33, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'KIITOS COUNTRY WOOD (база C)', unit: '12 кг', price: 6509.48, coverage: 0, category: 'KIITOS', description: '' },
        { name: 'SAPFIR', unit: '0,9 кг', price: 286.33, coverage: 0, category: 'KIITOS', description: 'Бесцветный' },
        { name: 'SAPFIR', unit: '2,5 кг', price: 762.01, coverage: 0, category: 'KIITOS', description: 'Бесцветный' },
        { name: 'SAPFIR', unit: '0,9 кг', price: 329.82, coverage: 0, category: 'KIITOS', description: 'Тик' },
        { name: 'SAPFIR', unit: '2,5 кг', price: 882.87, coverage: 0, category: 'KIITOS', description: 'Тик' },
        { name: 'SAPFIR', unit: '0,9 кг', price: 293.04, coverage: 0, category: 'KIITOS', description: 'Сосна' },
        { name: 'SAPFIR', unit: '2,5 кг', price: 776.93, coverage: 0, category: 'KIITOS', description: 'Сосна' },
        { name: 'SAPFIR', unit: '0,9 кг', price: 320.58, coverage: 0, category: 'KIITOS', description: 'Палисандр' },
        { name: 'SAPFIR', unit: '2,5 кг', price: 849.66, coverage: 0, category: 'KIITOS', description: 'Палисандр' },
        { name: 'SAPFIR', unit: '0,9 кг', price: 315.9, coverage: 0, category: 'KIITOS', description: 'Орегон' },
        { name: 'SAPFIR', unit: '2,5 кг', price: 838.24, coverage: 0, category: 'KIITOS', description: 'Орегон' },
        { name: 'SAPFIR', unit: '0,9 кг', price: 312.51, coverage: 0, category: 'KIITOS', description: 'Дуб' },
        { name: 'SAPFIR', unit: '2,5 кг', price: 834.57, coverage: 0, category: 'KIITOS', description: 'Дуб' },
        { name: 'SAPFIR', unit: '0,9 кг', price: 314.18, coverage: 0, category: 'KIITOS', description: 'Махагон' },
        { name: 'SAPFIR', unit: '2,5 кг', price: 838.24, coverage: 0, category: 'KIITOS', description: 'Махагон' },
        { name: 'SAPFIR', unit: '0,9 кг', price: 307.3, coverage: 0, category: 'KIITOS', description: 'Орех' },
        { name: 'SAPFIR', unit: '2,5 кг', price: 823.42, coverage: 0, category: 'KIITOS', description: 'Орех' },
        { name: 'SAPFIR', unit: '0,9 кг', price: 318.17, coverage: 0, category: 'KIITOS', description: 'Груша' },
        { name: 'SAPFIR', unit: '2,5 кг', price: 841.95, coverage: 0, category: 'KIITOS', description: 'Груша' },
        { name: 'SAPFIR', unit: '0,9 кг', price: 315.2, coverage: 0, category: 'KIITOS', description: 'Рябина' },
        { name: 'SAPFIR', unit: '2,5 кг', price: 838.24, coverage: 0, category: 'KIITOS', description: 'Рябина' },
        { name: 'SAPFIR', unit: '0,9 кг', price: 299.92, coverage: 0, category: 'KIITOS', description: 'Калужница' },
        { name: 'SAPFIR', unit: '2,5 кг', price: 797.49, coverage: 0, category: 'KIITOS', description: 'Калужница' },
        { name: 'SAPFIR', unit: '0,9 кг', price: 311.59, coverage: 0, category: 'KIITOS', description: 'Иней' },
        { name: 'SAPFIR', unit: '2,5 кг', price: 827.13, coverage: 0, category: 'KIITOS', description: 'Иней' },
        { name: 'DEEP MATT', unit: '0,45 л / 0,64 кг', price: 1830.0, coverage: 0, category: 'OLSTA ARCHITECT', description: 'Глубокоматовая краска премиум-класса. Уникальная цветопередача (база A)' },
        { name: 'DEEP MATT (база A)', unit: '0,90 л / 1,28 кг', price: 3150.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'DEEP MATT (база A)', unit: '2,70 л / 3,84 кг', price: 7830.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'DEEP MATT (база A)', unit: '9,00 л / 12,80 кг', price: 23380.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'DEEP MATT (база C, насыщ. тона)', unit: '0,45 л', price: 1630.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'DEEP MATT (база C)', unit: '0,90 л', price: 2750.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'DEEP MATT (база C)', unit: '2,70 л', price: 6710.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'DEEP MATT (база C)', unit: '9,00 л', price: 19720.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'BASIC MATT', unit: '0,45 л', price: 1830.0, coverage: 0, category: 'OLSTA ARCHITECT', description: 'Матовая краска премиум-класса (база A)' },
        { name: 'BASIC MATT (база A)', unit: '0,90 л', price: 3150.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'BASIC MATT (база A)', unit: '2,70 л', price: 7830.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'BASIC MATT (база A)', unit: '9,00 л', price: 23380.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'BASIC MATT (база C)', unit: '0,45 л', price: 1630.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'BASIC MATT (база C)', unit: '0,90 л', price: 2750.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'BASIC MATT (база C)', unit: '2,70 л', price: 6710.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'BASIC MATT (база C)', unit: '9,00 л', price: 19720.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'EGG SHELL', unit: '0,45 л', price: 1980.0, coverage: 0, category: 'OLSTA ARCHITECT', description: 'Полуматовая (скорлупа) краска премиум-класса (база A)' },
        { name: 'EGG SHELL (база A)', unit: '0,90 л', price: 3420.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'EGG SHELL (база A)', unit: '2,70 л', price: 8540.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'EGG SHELL (база A)', unit: '9,00 л', price: 24910.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'EGG SHELL (база C)', unit: '0,45 л', price: 1630.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'EGG SHELL (база C)', unit: '0,90 л', price: 2750.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'EGG SHELL (база C)', unit: '2,70 л', price: 6910.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'EGG SHELL (база C)', unit: '9,00 л', price: 21350.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'MEDIUM GLOSS', unit: '0,90 л', price: 3450.0, coverage: 0, category: 'OLSTA ARCHITECT', description: 'Глянцевая краска премиум-класса (база A)' },
        { name: 'MEDIUM GLOSS (база A)', unit: '2,70 л', price: 8540.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'MEDIUM GLOSS (база A)', unit: '9,00 л', price: 24910.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'MEDIUM GLOSS (база C)', unit: '0,90 л', price: 3050.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'MEDIUM GLOSS (база C)', unit: '2,70 л', price: 7520.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'PRIMER', unit: '3 л / 3 кг', price: 3560.0, coverage: 0, category: 'OLSTA ARCHITECT', description: 'Водно-дисперс. грунт для внутренних работ, выравнивает впитываемость основания' },
        { name: 'PRO PRIMER', unit: '2,70 л / 4,20 кг', price: 3150.0, coverage: 0, category: 'OLSTA ARCHITECT', description: 'Грунт с высокой кроющей способностью, для цветового выравнивания; машинное нанесение' },
        { name: 'PRO PRIMER', unit: '9,00 л / 14,00 кг', price: 8940.0, coverage: 0, category: 'OLSTA ARCHITECT', description: '' },
        { name: 'CHALKY PAINT', unit: '0,45 л / 0,55 кг', price: 1510.0, coverage: 0, category: 'OLSTA', description: 'Шелк.-матовая краска для мебели 2 в 1, не требует грунтовки (база A)' },
        { name: 'CHALKY PAINT (база A)', unit: '0,90 л / 1,09 кг', price: 2390.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'CHALKY PAINT (база C)', unit: '0,45 л', price: 1290.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'CHALKY PAINT (база C)', unit: '0,90 л', price: 2040.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'CHALKY FURNITURE PAINT', unit: '0,45 л / 0,55 кг', price: 1440.0, coverage: 0, category: 'OLSTA', description: 'Полуглянцевая краска для мебели во влажных помещениях, без защиты (база A)' },
        { name: 'CHALKY FURNITURE PAINT (база A)', unit: '0,90 л / 1,09 кг', price: 2290.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'CHALKY FURNITURE PAINT (база C)', unit: '0,45 л', price: 1220.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'CHALKY FURNITURE PAINT (база C)', unit: '0,90 л', price: 1930.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'CERAMIC PAINT', unit: '0,90 л', price: 1830.0, coverage: 0, category: 'OLSTA', description: 'Акриловая глубокоматовая, ультраустойчивое покрытие для коммерции (база A)' },
        { name: 'CERAMIC PAINT (база A)', unit: '2,70 л', price: 5030.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'CERAMIC PAINT (база A)', unit: '9,00 л', price: 15250.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'CERAMIC PAINT (база C)', unit: '0,90 л', price: 1420.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'CERAMIC PAINT (база C)', unit: '2,70 л', price: 4200.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'CERAMIC PAINT (база C)', unit: '9,00 л', price: 12710.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'ДЛЯ ОБОЕВ, СТЕН И ПОТОЛКОВ', unit: '0,90 л', price: 860.0, coverage: 0, category: 'OLSTA', description: 'Матовая, для всех типов обоев под покраску (база A)' },
        { name: 'ДЛЯ ОБОЕВ, СТЕН И ПОТОЛКОВ (база A)', unit: '2,70 л', price: 2140.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'ДЛЯ ОБОЕВ, СТЕН И ПОТОЛКОВ (база A)', unit: '9,00 л', price: 6300.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'ДЛЯ ОБОЕВ, СТЕН И ПОТОЛКОВ (база C)', unit: '0,90 л', price: 830.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'ДЛЯ ОБОЕВ, СТЕН И ПОТОЛКОВ (база C)', unit: '2,70 л', price: 2030.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'ДЛЯ ОБОЕВ, СТЕН И ПОТОЛКОВ (база C)', unit: '9,00 л', price: 6200.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'ДЛЯ ВЛАЖНЫХ ПОМЕЩЕНИЙ', unit: '0,90 л', price: 910.0, coverage: 0, category: 'OLSTA', description: 'Влагостойкая матовая, защита от плесени и грибка (база A)' },
        { name: 'ДЛЯ ВЛАЖНЫХ ПОМЕЩЕНИЙ (база A)', unit: '2,70 л', price: 2240.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'ДЛЯ ВЛАЖНЫХ ПОМЕЩЕНИЙ (база A)', unit: '9,00 л', price: 6410.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'ДЛЯ ВЛАЖНЫХ ПОМЕЩЕНИЙ (база C)', unit: '0,90 л', price: 850.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'ДЛЯ ВЛАЖНЫХ ПОМЕЩЕНИЙ (база C)', unit: '2,70 л', price: 2130.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'ДЛЯ ВЛАЖНЫХ ПОМЕЩЕНИЙ (база C)', unit: '9,00 л', price: 6300.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'KIDS & BEDROOM', unit: '0,90 л', price: 1610.0, coverage: 0, category: 'OLSTA', description: 'Гипоаллергенная акриловая, легко отмывается (база A)' },
        { name: 'KIDS & BEDROOM (база A)', unit: '2,70 л', price: 4170.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'KIDS & BEDROOM (база A)', unit: '9,00 л', price: 12910.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'KIDS & BEDROOM (база C)', unit: '0,90 л', price: 1180.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'KIDS & BEDROOM (база C)', unit: '2,70 л', price: 3200.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'KIDS & BEDROOM (база C)', unit: '9,00 л', price: 9660.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'KITCHEN & BATHROOM', unit: '0,90 л', price: 1610.0, coverage: 0, category: 'OLSTA', description: 'Акриловая, устойчива к интенс. мытью с моющими средствами (база A)' },
        { name: 'KITCHEN & BATHROOM (база A)', unit: '2,70 л', price: 4170.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'KITCHEN & BATHROOM (база A)', unit: '9,00 л', price: 12910.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'KITCHEN & BATHROOM (база C)', unit: '0,90 л', price: 1180.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'KITCHEN & BATHROOM (база C)', unit: '2,70 л', price: 3200.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'KITCHEN & BATHROOM (база C)', unit: '9,00 л', price: 9660.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WALL & CEILING', unit: '0,90 л', price: 1420.0, coverage: 0, category: 'OLSTA', description: 'Моющаяся высокоукрывистая акриловая (база A)' },
        { name: 'WALL & CEILING (база A)', unit: '2,70 л', price: 3860.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WALL & CEILING (база A)', unit: '9,00 л', price: 11690.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WALL & CEILING (база C)', unit: '0,90 л', price: 1120.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WALL & CEILING (база C)', unit: '2,70 л', price: 2850.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WALL & CEILING (база C)', unit: '9,00 л', price: 8740.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'OFFICE & HALL', unit: '0,90 л', price: 1470.0, coverage: 0, category: 'OLSTA', description: 'Шелк.-матовая, износостойкая, паропроницаемая (база A)' },
        { name: 'OFFICE & HALL (база A)', unit: '2,70 л', price: 4070.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'OFFICE & HALL (база A)', unit: '9,00 л', price: 12710.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'OFFICE & HALL (база C)', unit: '0,90 л', price: 1120.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'OFFICE & HALL (база C)', unit: '2,70 л', price: 2950.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'OFFICE & HALL (база C)', unit: '9,00 л', price: 9350.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'CEILING', unit: '0,90 л', price: 970.0, coverage: 0, category: 'OLSTA', description: 'Глубокоматовая для потолков, безупречно белая, рассеивает свет (база A)' },
        { name: 'CEILING (база A)', unit: '2,70 л', price: 2610.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'CEILING (база A)', unit: '9,00 л', price: 7730.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'SOCKET PAINT', unit: '2,70 л', price: 4940.0, coverage: 0, category: 'OLSTA', description: 'Акриловая фасадная, шелк.-матовая, защита цоколя, срок 10+ лет (база A)' },
        { name: 'SOCKET PAINT (база A)', unit: '9,00 л', price: 13720.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'SOCKET PAINT (база C)', unit: '2,70 л', price: 4390.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'SOCKET PAINT (база C)', unit: '9,00 л', price: 12200.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'ФАСАДНАЯ акриловая', unit: '2,70 л', price: 2130.0, coverage: 0, category: 'OLSTA', description: 'Для минер. и дерев. оснований, укрывистая (база A)' },
        { name: 'ФАСАДНАЯ акриловая (база A)', unit: '9,00 л', price: 6310.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'ФАСАДНАЯ акриловая (база C)', unit: '2,70 л', price: 1930.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'ФАСАДНАЯ акриловая (база C)', unit: '9,00 л', price: 6000.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'ФАСАДНАЯ силиконизированная', unit: '2,70 л', price: 2340.0, coverage: 0, category: 'OLSTA', description: 'Влаго- и грязеустойчивая, паропроницаемая (база A)' },
        { name: 'ФАСАДНАЯ силиконизированная (база A)', unit: '9,00 л', price: 7020.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'ФАСАДНАЯ силиконизированная (база C)', unit: '2,70 л', price: 2130.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'ФАСАДНАЯ силиконизированная (база C)', unit: '9,00 л', price: 6410.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WOOD & METAL', unit: '0,45 л', price: 1160.0, coverage: 0, category: 'OLSTA', description: 'Универсальная для окон, дверей, радиаторов, метала, дерева (база A)' },
        { name: 'WOOD & METAL (база A)', unit: '0,90 л', price: 1980.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WOOD & METAL (база A)', unit: '2,70 л', price: 5690.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WOOD & METAL (база C)', unit: '0,45 л', price: 1090.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WOOD & METAL (база C)', unit: '0,90 л', price: 1880.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WOOD & METAL (база C)', unit: '2,70 л', price: 5290.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WOOD RENOVATOR', unit: '0,90 л', price: 1420.0, coverage: 0, category: 'OLSTA', description: 'Лазурь для хвойных и лиственных пород, срок 10+ лет (база C)' },
        { name: 'WOOD RENOVATOR (база C)', unit: '2,70 л', price: 4020.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WOOD RENOVATOR (база C)', unit: '9,00 л', price: 12200.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'EXTERIOR SILICONE', unit: '2,70 л', price: 5390.0, coverage: 0, category: 'OLSTA', description: 'Силиконовая, грязеотталкивающая, срок 10+ лет (база A)' },
        { name: 'EXTERIOR SILICONE (база A)', unit: '9,00 л', price: 17080.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'EXTERIOR SILICONE (база C)', unit: '2,70 л', price: 3660.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'EXTERIOR SILICONE (база C)', unit: '9,00 л', price: 11280.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WOOD PAINT', unit: '0,90 л', price: 1630.0, coverage: 0, category: 'OLSTA', description: 'Шелк.-матовая, антисептик, срок 15+ лет (база A)' },
        { name: 'WOOD PAINT (база A)', unit: '2,70 л', price: 4370.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WOOD PAINT (база A)', unit: '9,00 л', price: 14130.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WOOD PAINT (база C)', unit: '0,90 л', price: 1320.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WOOD PAINT (база C)', unit: '2,70 л', price: 3760.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WOOD PAINT (база C)', unit: '9,00 л', price: 11280.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'EXTERIOR ACRYLIC', unit: '2,70 л', price: 4370.0, coverage: 0, category: 'OLSTA', description: 'Акриловая, высокоукрывистая, повышен. износостойкость, срок 10+ лет (база A)' },
        { name: 'EXTERIOR ACRYLIC (база A)', unit: '9,00 л', price: 14440.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'EXTERIOR ACRYLIC (база C)', unit: '2,70 л', price: 3360.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'EXTERIOR ACRYLIC (база C)', unit: '9,00 л', price: 11240.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'PRIMER CONCENTRATE', unit: '0,90 л', price: 460.0, coverage: 0, category: 'OLSTA', description: 'Грунт-концентрат для наружных и внутренних работ' },
        { name: 'MULTI PRIMER', unit: '0,90 л', price: 2270.0, coverage: 0, category: 'OLSTA', description: 'Адгезионный грунт для металлов, стекла, ПВХ, дерева, защита от коррозии' },
        { name: 'INTERIOR & EXTERIOR PRIMER', unit: '5 л', price: 1220.0, coverage: 0, category: 'OLSTA', description: 'Водно-дисп. грунт для наружных и внутренних работ' },
        { name: 'INTERIOR & EXTERIOR PRIMER', unit: '10 л', price: 2140.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'SILICONE PRIMER', unit: '10 л', price: 2750.0, coverage: 0, category: 'OLSTA', description: 'Силиконовый грунт с высокой проникающей способностью' },
        { name: 'WOOD PRIMER', unit: '5 л', price: 3560.0, coverage: 0, category: 'OLSTA', description: 'Грунт для защиты древесины от плесени, синевы, гнили (антисептик)' },
        { name: 'PIGMENTED PRIMER', unit: '2,90 л / 4 кг', price: 1620.0, coverage: 0, category: 'OLSTA', description: 'Укрывающий грунт для цветового выравнивания основания' },
        { name: 'PIGMENTED PRIMER', unit: '10 л / 14 кг', price: 4420.0, coverage: 0, category: 'OLSTA', description: '' },
        { name: 'WATERBLOCK', unit: '3 л / 3,5 кг', price: 2640.0, coverage: 0, category: 'OLSTA', description: 'Интерьерный грунт-гидроизоляция для санузлов и душевых. «Тёплые полы».' },
        { name: 'LIME PAINT', unit: '1 кг', price: 2440.0, coverage: 0, category: 'DECORAZZA', description: 'Известковая краска на натур. гашёной извести. Глубокоматовая, антисептическая.' },
        { name: 'LIME PAINT', unit: '6 кг', price: 14440.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'ALCANTARA', unit: '0,7 кг / 1 л', price: 4270.0, coverage: 0, category: 'DECORAZZA', description: 'Покрытие с эффектом замши / нубука. Уникальная тактильная текстура.' },
        { name: 'ALCANTARA', unit: '3,5 кг / 5 л', price: 18090.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'WALL ARTE', unit: '1,2 кг', price: 1220.0, coverage: 0, category: 'DECORAZZA', description: 'Эффект художественного гладкого бетона. Акварельный цветопереход.' },
        { name: 'WALL ARTE', unit: '6 кг', price: 4880.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'VELOURS', unit: '1,2 кг', price: 3460.0, coverage: 0, category: 'DECORAZZA', description: 'Эффект мягкого бархата. Легко реставрируется. Палитра Паскаля Граво.' },
        { name: 'VELOURS', unit: '6 кг', price: 14540.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'CRAQUELUR', unit: '1 кг / 1 л', price: 1730.0, coverage: 0, category: 'DECORAZZA', description: 'Эффект трещин / состаренной поверхности. Не колеруется.' },
        { name: 'ARETINO', unit: '1 кг / 1 л', price: 3360.0, coverage: 0, category: 'DECORAZZA', description: 'Перламутровые переливы, тонкотекстурное. Широкая палитра.' },
        { name: 'ARETINO', unit: '5 кг / 5 л', price: 14030.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'BREZZA', unit: '1 кг / 1 л', price: 2850.0, coverage: 0, category: 'DECORAZZA', description: 'Эффект песчаных вихрей. Матовые частицы + перламутр.' },
        { name: 'BREZZA', unit: '5 кг / 5 л', price: 10770.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'EFFETTO METALLICO ARGENTO', unit: '1 кг / 1 л', price: 3050.0, coverage: 0, category: 'DECORAZZA', description: 'Металлизир. краска, серебро' },
        { name: 'EFFETTO METALLICO BIANCO', unit: '1 кг / 1 л', price: 1630.0, coverage: 0, category: 'DECORAZZA', description: 'белое серебро' },
        { name: 'EFFETTO METALLICO ORO', unit: '1 кг / 1 л', price: 2950.0, coverage: 0, category: 'DECORAZZA', description: 'золото' },
        { name: 'LUCETEZZA ARGENTO', unit: '0,4 кг', price: 1940.0, coverage: 0, category: 'DECORAZZA', description: 'Перламутровые песчаные вихри, серебро' },
        { name: 'LUCETEZZA ARGENTO', unit: '1 кг', price: 3350.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'LUCETEZZA ARGENTO', unit: '5 кг', price: 13930.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'LUCETEZZA ALLUMINIUM', unit: '1 кг', price: 5080.0, coverage: 0, category: 'DECORAZZA', description: 'алюминий' },
        { name: 'LUCETEZZA ALLUMINIUM', unit: '5 кг', price: 21550.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'LUCETEZZA ORO', unit: '1 кг', price: 5080.0, coverage: 0, category: 'DECORAZZA', description: 'золото' },
        { name: 'SETA da VINCI', unit: '1 кг', price: 4470.0, coverage: 0, category: 'DECORAZZA', description: 'Перламутровый шёлк, уникальная визуальная глубина.' },
        { name: 'SETA da VINCI', unit: '5 кг', price: 19520.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'SETA ORO', unit: '1 кг', price: 4680.0, coverage: 0, category: 'DECORAZZA', description: 'Натуральный шёлк с переливами, золото' },
        { name: 'SETA ARGENTO', unit: '0,4 кг', price: 1940.0, coverage: 0, category: 'DECORAZZA', description: 'серебро' },
        { name: 'SETA ARGENTO', unit: '1 кг', price: 3350.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'SETA ARGENTO', unit: '5 кг', price: 13930.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'VELLUTO', unit: '1 кг', price: 3350.0, coverage: 0, category: 'DECORAZZA', description: 'Матовый шёлк с бархатистой текстурой.' },
        { name: 'VELLUTO', unit: '5 кг', price: 14030.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'STUCCO VENEZIANO', unit: '7 кг', price: 6300.0, coverage: 0, category: 'DECORAZZA', description: 'Эффект вен. штукатурки (акрил). Имитация полированного камня.' },
        { name: 'CALCE VENEZIANA', unit: '6 кг', price: 8640.0, coverage: 0, category: 'DECORAZZA', description: 'Классическая вен. штукатурка (известь). Зеркальный глянец.' },
        { name: 'ART BETON', unit: '4 кг', price: 4020.0, coverage: 0, category: 'DECORAZZA', description: 'Художественный бетон. Светло-серый готовый оттенок.' },
        { name: 'ART BETON', unit: '9 кг', price: 8440.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'TRAVERTINO NATURALE', unit: '7 кг', price: 8840.0, coverage: 0, category: 'DECORAZZA', description: 'Натур. известковое фактурное покрытие. Антисептик. Легко глянцуется.' },
        { name: 'TRAVERTINO NATURALE', unit: '15 кг', price: 16880.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'ROMANO', unit: '14 кг', price: 9450.0, coverage: 0, category: 'DECORAZZA', description: 'Травертин. Наружные и внутренние. Срок 10+ лет.' },
        { name: 'TRAVERTA', unit: '7 кг', price: 6100.0, coverage: 0, category: 'DECORAZZA', description: 'Природный травертин. Устойчив к мытью и истиранию.' },
        { name: 'TRAVERTA', unit: '15 кг', price: 11280.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'RUSTIC', unit: '15 кг', price: 6000.0, coverage: 0, category: 'DECORAZZA', description: 'Необработанный камень. Повышенная износостойкость. Не колеруется.' },
        { name: 'BARILIEVO', unit: '4 кг', price: 3150.0, coverage: 0, category: 'DECORAZZA', description: 'Высокопластичное. Широкий набор декоративных эффектов.' },
        { name: 'BARILIEVO', unit: '15 кг', price: 9860.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'SOLLIEVO', unit: '15 кг', price: 10470.0, coverage: 0, category: 'DECORAZZA', description: 'Со спец. волокнами для художественных рельефов и барельефов. Не колеруется.' },
        { name: 'MICROCEMENTO FRONTE', unit: '3 кг (набор)', price: 4880.0, coverage: 0, category: 'DECORAZZA', description: 'Мелкая фракция. Влаго- и износостойкое. Для влажных помещений.' },
        { name: 'MICROCEMENTO FRONTE', unit: '15,3 кг (набор)', price: 23080.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'MICROCEMENTO STRUTTURA', unit: '7,2 кг (набор)', price: 10070.0, coverage: 0, category: 'DECORAZZA', description: 'Крупная фракция.' },
        { name: 'MICROCEMENTO STRUTTURA', unit: '18 кг (набор)', price: 24600.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'MICROCEMENTO PROTETTO MATTE', unit: '0,68 кг', price: 12000.0, coverage: 0, category: 'DECORAZZA', description: '2К ПУ-лак для системы микроцемента (компонент A)' },
        { name: 'MICROCEMENTO PROTETTO MATTE (компонент B)', unit: '0,15 кг', price: 3560.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'CALCE FINITURA', unit: '1 кг / 1 л', price: 1420.0, coverage: 0, category: 'DECORAZZA', description: 'Защитная лессировка для известковых покрытий' },
        { name: 'FINITURA', unit: '1 кг / 1 л', price: 1320.0, coverage: 0, category: 'DECORAZZA', description: 'Влагозащитная пропитка, не изменяет вид покрытия. Не колеруется.' },
        { name: 'CERA di VENEZIANO NOVA', unit: '0,8 кг / 1 л', price: 4270.0, coverage: 0, category: 'DECORAZZA', description: 'Воск для вен. штукатурки. Зеркальный блеск.' },
        { name: 'FLEUR DECO INCOLORE', unit: '0,4 кг / 0,4 л', price: 1640.0, coverage: 0, category: 'DECORAZZA', description: 'Защитный лак шелк.-матовый' },
        { name: 'FLEUR DECO INCOLORE', unit: '1 кг / 1 л', price: 2640.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'PERLA VERNICI ARGENTO', unit: '0,4 кг / 0,4 л', price: 1950.0, coverage: 0, category: 'DECORAZZA', description: 'Перламутровая лессировка. Подчёркивает рисунок.' },
        { name: 'PERLA VERNICI ARGENTO', unit: '1 кг / 1 л', price: 3250.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'PERLA VERNICI ARGENTO', unit: '2,5 кг / 2,5 л', price: 6610.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'PERLA VERNICI ORO', unit: '1 кг / 1 л', price: 3950.0, coverage: 0, category: 'DECORAZZA', description: 'золото' },
        { name: 'PERLA VERNICI CHAMELEON', unit: '1 кг / 1 л', price: 3950.0, coverage: 0, category: 'DECORAZZA', description: 'хамелеон' },
        { name: 'PASTELLO VERNICI', unit: '0,4 кг / 0,4 л', price: 1530.0, coverage: 0, category: 'DECORAZZA', description: 'Матовая лессировка, не желтеет от УФ. Срок 10+ лет.' },
        { name: 'PASTELLO VERNICI', unit: '1 кг / 1 л', price: 2540.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'PASTELLO VERNICI', unit: '5 кг / 5 л', price: 8540.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'CERA DECOR', unit: '0,35 кг / 0,4 л', price: 2540.0, coverage: 0, category: 'DECORAZZA', description: 'Лессировка на натур. воске. Матовый блеск + тактильные свойства.' },
        { name: 'CERA DECOR', unit: '0,9 кг / 1 л', price: 4880.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'CERA DECOR', unit: '2,3 кг / 2,5 л', price: 9250.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'MICA', unit: '0,1 кг', price: 910.0, coverage: 0, category: 'DECORAZZA', description: 'Добавка из натуральной слюды (в фактурные покрытия)' },
        { name: 'LUCENTE Glitter Argento', unit: '0,03 кг', price: 1370.0, coverage: 0, category: 'DECORAZZA', description: 'Добавка с глиттером, серебро' },
        { name: 'LUCENTE Glitter Oro', unit: '0,03 кг', price: 1520.0, coverage: 0, category: 'DECORAZZA', description: 'золото' },
        { name: 'LUCENTE Perlamuter Diamante', unit: '0,03 кг', price: 4880.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'LUCENTE Perlamuter Amber', unit: '0,03 кг', price: 4880.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'LUCENTE Perlamuter Rubin', unit: '0,03 кг', price: 4880.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'LUCENTE Perlamuter Argento', unit: '0,03 кг', price: 1420.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'LUCENTE Perlamuter Oro', unit: '0,03 кг', price: 4880.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'FIORA', unit: '0,90 л / 1,30 кг', price: 1730.0, coverage: 0, category: 'DECORAZZA', description: 'Влагостойкая интерьерная краска (подготовка под декор. покрытия). База A' },
        { name: 'FIORA (база A)', unit: '2,70 л / 3,80 кг', price: 4170.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'FIORA (база A)', unit: '9,00 л / 12,60 кг', price: 12810.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'FIORA (база C)', unit: '0,90 л', price: 1320.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'FIORA (база C)', unit: '2,70 л', price: 3050.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'BASE', unit: '1,5 кг', price: 1170.0, coverage: 0, category: 'DECORAZZA', description: 'Грунт-краска под гладкие декор. покрытия. Высокоукрывистая. Колеруется.' },
        { name: 'BASE', unit: '4 кг', price: 2440.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'BASE', unit: '15 кг', price: 7930.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'PRIEMER DI QUARZO', unit: '1,5 кг', price: 920.0, coverage: 0, category: 'DECORAZZA', description: 'Грунт-краска с кварц. наполнителем под фактурные покрытия. Колеруется.' },
        { name: 'PRIEMER DI QUARZO', unit: '7 кг', price: 3360.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'PRIEMER DI QUARZO', unit: '14 кг', price: 6300.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'PRIMER DECORAZZA', unit: '5 кг / 5 л', price: 1320.0, coverage: 0, category: 'DECORAZZA', description: 'Водно-дисп. грунт, выравнивает впитываемость. Не колеруется.' },
        { name: 'PRIMER DECORAZZA', unit: '10 кг / 10 л', price: 2440.0, coverage: 0, category: 'DECORAZZA', description: '' },
        { name: 'COLORIX', unit: '4,5 кг', price: 5290.0, coverage: 0, category: 'BAYRAMIX', description: 'Покрытие с цветными чипсами (флоками). Стойкость к мех. воздействиям. (ОГРАНИЧЕННЫЕ ОСТАТКИ)' },
        { name: 'COLORIX', unit: '9 кг', price: 9910.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'COLORIX ПЕРЕЛИВ', unit: '4,5 кг', price: 7220.0, coverage: 0, category: 'BAYRAMIX', description: 'Флоки с эффектом перламутра. (ОГРАНИЧЕННЫЕ ОСТАТКИ)' },
        { name: 'COLORIX ПЕРЕЛИВ', unit: '9 кг', price: 13320.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'Лессирующий состав', unit: '1 кг / 1 л', price: 860.0, coverage: 0, category: 'BAYRAMIX', description: 'Перламутровая лессировка. Жемчужный эффект.' },
        { name: 'BRILLIANCE Gold', unit: '0,03 кг', price: 970.0, coverage: 0, category: 'BAYRAMIX', description: 'Добавка на перламутровых глиттерах, золото' },
        { name: 'BRILLIANCE Silver', unit: '0,03 кг', price: 510.0, coverage: 0, category: 'BAYRAMIX', description: 'серебро' },
        { name: 'Мраморная штукатурка', unit: '7 кг', price: 1700.0, coverage: 0, category: 'BAYRAMIX', description: 'Средняя фракция N 0,5–1,0 мм (KW-N, MW-N, RW-N)' },
        { name: 'Мраморная штукатурка', unit: '15 кг', price: 3290.0, coverage: 0, category: 'BAYRAMIX', description: 'Средняя фракция N 0,5–1,0 мм' },
        { name: 'Мраморная штукатурка', unit: '15 кг', price: 3410.0, coverage: 0, category: 'BAYRAMIX', description: 'Средняя фракция N 0,5–1,0 мм (PR-N, KG-N)' },
        { name: 'Мраморная штукатурка', unit: '7 кг', price: 1700.0, coverage: 0, category: 'BAYRAMIX', description: 'Крупная фракция K 1,0–1,5 мм (MW-K)' },
        { name: 'Мраморная штукатурка', unit: '7 кг', price: 1760.0, coverage: 0, category: 'BAYRAMIX', description: 'Крупная фракция K 1,0–1,5 мм (EG-K, KG-K, PR-K, RS-K)' },
        { name: 'Мраморная штукатурка', unit: '15 кг', price: 3290.0, coverage: 0, category: 'BAYRAMIX', description: 'Крупная фракция K 1,0–1,5 мм (MW-K)' },
        { name: 'Мраморная штукатурка', unit: '15 кг', price: 3410.0, coverage: 0, category: 'BAYRAMIX', description: 'Крупная фракция K 1,0–1,5 мм (EG-K, KG-K, PR-K, RS-K)' },
        { name: 'ECOSTONE', unit: '15 кг', price: 3290.0, coverage: 0, category: 'BAYRAMIX', description: 'Средняя фракция N 0,5–1,0 мм' },
        { name: 'ECOSTONE', unit: '15 кг', price: 3290.0, coverage: 0, category: 'BAYRAMIX', description: 'Крупная фракция K 1,0–1,5 мм' },
        { name: 'MICROMINERAL', unit: '15 кг', price: 5290.0, coverage: 0, category: 'BAYRAMIX', description: 'Микрофракция 0,2–0,5 мм. Машинное нанесение.' },
        { name: 'MINERAL', unit: '15 кг', price: 5320.0, coverage: 0, category: 'BAYRAMIX', description: 'Средняя фракция 0,7–1,2 мм. Срок 10+ лет.' },
        { name: 'MINERAL', unit: '15 кг', price: 5490.0, coverage: 0, category: 'BAYRAMIX', description: 'Средняя фракция 0,7–1,2 мм (цвета 381–391, перламутр)' },
        { name: 'MINERAL', unit: '15 кг', price: 5320.0, coverage: 0, category: 'BAYRAMIX', description: 'Крупная фракция 1,2–1,5 мм' },
        { name: 'MACROMINERAL', unit: '15 кг', price: 5030.0, coverage: 0, category: 'BAYRAMIX', description: 'Крупная фракция 1,5–2,0 мм' },
        { name: 'MACROMINERAL', unit: '15 кг', price: 6100.0, coverage: 0, category: 'BAYRAMIX', description: '1,5–2,0 мм (цвета 1021, 1022, 1036)' },
        { name: 'MACROMINERAL XL', unit: '15 кг', price: 4980.0, coverage: 0, category: 'BAYRAMIX', description: 'Фракция 2,0–2,5 мм' },
        { name: 'GOLD', unit: '15 кг', price: 7740.0, coverage: 0, category: 'BAYRAMIX', description: 'Мраморная штукатурка с перламутровым эффектом, 1,0–1,5 мм' },
        { name: 'i-FLEX', unit: '14 кг', price: 9960.0, coverage: 0, category: 'BAYRAMIX', description: 'Эластомерная штукатурка. Скрывает трещины. Срок 10+ лет.' },
        { name: 'GRAVOL', unit: '7 кг', price: 1730.0, coverage: 0, category: 'BAYRAMIX', description: 'Камешковая «шуба». Фракция 1,5 мм.' },
        { name: 'GRAVOL', unit: '15 кг', price: 3670.0, coverage: 0, category: 'BAYRAMIX', description: 'Фракция 1,5 мм' },
        { name: 'GRAVOL', unit: '15 кг', price: 3670.0, coverage: 0, category: 'BAYRAMIX', description: 'Фракция 2,5 мм' },
        { name: 'PALTA', unit: '15 кг', price: 4580.0, coverage: 0, category: 'BAYRAMIX', description: 'Камешковая с мраморной крошкой.' },
        { name: 'RULMIX', unit: '15 кг', price: 3660.0, coverage: 0, category: 'BAYRAMIX', description: '«Мелкая шуба», мелкорельефное покрытие.' },
        { name: 'TERATEX', unit: '15 кг', price: 3810.0, coverage: 0, category: 'BAYRAMIX', description: '«Крупная шуба», моделируемая. Ручное и машинное нанесение.' },
        { name: 'TERATEX FINE', unit: '15 кг', price: 5830.0, coverage: 0, category: 'BAYRAMIX', description: 'Мелкорельефное. Машинное нанесение. Экономичный расход.' },
        { name: 'BAYTERA', unit: '15 кг', price: 4470.0, coverage: 0, category: 'BAYRAMIX', description: '«Короед» мелкая фракция 2 мм' },
        { name: 'BAYTERA', unit: '15 кг', price: 4470.0, coverage: 0, category: 'BAYRAMIX', description: '«Короед» крупная фракция 3 мм' },
        { name: 'SANDECO', unit: '7 кг', price: 1780.0, coverage: 0, category: 'BAYRAMIX', description: '«Песок» с декор. эффектом, мелкотекстурная (база A)' },
        { name: 'SANDECO (база A)', unit: '15 кг', price: 3780.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'SANDECO (база C)', unit: '6 кг', price: 1530.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'SANDECO (база C)', unit: '13 кг', price: 3050.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'DECOSTONE', unit: '15 кг', price: 3780.0, coverage: 0, category: 'BAYRAMIX', description: '«Короед» с грубым природным рисунком, мелкая 2 мм' },
        { name: 'DECOSTONE', unit: '15 кг', price: 3850.0, coverage: 0, category: 'BAYRAMIX', description: '«Короед» крупная 3 мм' },
        { name: 'GRAVOL Силиконовый', unit: '15 кг', price: 4680.0, coverage: 0, category: 'BAYRAMIX', description: 'Камешковая «шуба». Фракция 1,5 мм.' },
        { name: 'GRAVOL Силиконовый', unit: '15 кг', price: 4680.0, coverage: 0, category: 'BAYRAMIX', description: 'Фракция 2,5 мм' },
        { name: 'BAYTERA Силиконовая', unit: '15 кг', price: 4980.0, coverage: 0, category: 'BAYRAMIX', description: '«Короед» мелкая 2 мм' },
        { name: 'BAYTERA Силиконовая', unit: '15 кг', price: 4980.0, coverage: 0, category: 'BAYRAMIX', description: '«Короед» крупная 3 мм' },
        { name: 'ASTAR FIX', unit: '5 л', price: 850.0, coverage: 0, category: 'BAYRAMIX', description: 'Водно-дисп. грунт для наружных и внутренних работ' },
        { name: 'ASTAR FIX', unit: '10 л', price: 1530.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'Силиконовый праймер', unit: '10 л', price: 2030.0, coverage: 0, category: 'BAYRAMIX', description: 'Грунт с силик. эмульсией. Повышенная адгезия.' },
        { name: 'ASTAR УКРЫВАЮЩИЙ', unit: '4,5 л / 7 кг', price: 1730.0, coverage: 0, category: 'BAYRAMIX', description: 'Грунт с высокой кроющей способностью' },
        { name: 'ASTAR УКРЫВАЮЩИЙ', unit: '9,5 л / 15 кг', price: 3560.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'ASTAR КВАРЦЕВЫЙ', unit: '2,5 л / 4 кг', price: 1180.0, coverage: 0, category: 'BAYRAMIX', description: 'Грунт с кварц. наполнителем под фактурные покрытия. Колеруется.' },
        { name: 'ASTAR КВАРЦЕВЫЙ', unit: '4,5 л / 7 кг', price: 1820.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'ASTAR КВАРЦЕВЫЙ', unit: '9,5 л / 15 кг', price: 3960.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'Лак BS-35', unit: '0,9 л', price: 1220.0, coverage: 0, category: 'BAYRAMIX', description: 'Защитный лак матовый для наружных и внутренних работ (мин. и дерев. основания)' },
        { name: 'Лак BS-35', unit: '5 л', price: 4980.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'Лак BS-18', unit: '5 л', price: 3460.0, coverage: 0, category: 'BAYRAMIX', description: 'Защитный лак матовый для внутренних работ' },
        { name: 'PLASTIC EXTRA', unit: '0,90 л', price: 700.0, coverage: 0, category: 'BAYRAMIX', description: 'Матовая, высокая эксплуатационная нагрузка, влажная уборка. (ОГРАНИЧЕННЫЕ ОСТАТКИ)' },
        { name: 'PLASTIC EXTRA', unit: '2,70 л', price: 1930.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'PLASTIC EXTRA', unit: '9,00 л', price: 6000.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'PLASTIC PROFI', unit: '0,90 л', price: 820.0, coverage: 0, category: 'BAYRAMIX', description: 'Матовая, нормальная нагрузка, влажная уборка (база A)' },
        { name: 'PLASTIC PROFI (база A)', unit: '2,70 л', price: 1910.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'PLASTIC PROFI (база A)', unit: '9,00 л', price: 5830.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'PLASTIC PROFI (база C, насыщ. тона)', unit: '0,90 л', price: 850.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'PLASTIC PROFI (база C)', unit: '2,70 л', price: 1910.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'PLASTIC PROFI (база C)', unit: '9,00 л', price: 5830.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'SILICON PROFI', unit: '0,90 л', price: 950.0, coverage: 0, category: 'BAYRAMIX', description: 'Силиконовая. Влаго- и грязеустойч. Срок 12+ лет (база A)' },
        { name: 'SILICON PROFI (база A)', unit: '2,70 л', price: 2330.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'SILICON PROFI (база A)', unit: '4,50 л', price: 3600.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'SILICON PROFI (база A)', unit: '9,00 л', price: 7000.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'SILICON PROFI (база C)', unit: '0,90 л', price: 950.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'SILICON PROFI (база C)', unit: '2,70 л', price: 2330.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'SILICON PROFI (база C)', unit: '4,50 л', price: 3600.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'SILICON PROFI (база C)', unit: '9,00 л', price: 7000.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'ACRILIC PROFI', unit: '0,90 л', price: 830.0, coverage: 0, category: 'BAYRAMIX', description: 'Акриловая для фасадов и интерьеров. Срок 7+ лет. (база A)' },
        { name: 'ACRILIC PROFI (база A)', unit: '2,70 л', price: 2120.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'ACRILIC PROFI (база A)', unit: '9,00 л', price: 6250.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'ACRILIC PROFI (база C)', unit: '0,90 л', price: 830.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'ACRILIC PROFI (база C)', unit: '2,70 л', price: 2120.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'ACRILIC PROFI (база C)', unit: '9,00 л', price: 6250.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'ULTRA DURABLE', unit: '2,70 л', price: 2540.0, coverage: 0, category: 'BAYRAMIX', description: 'Усиленная силик. эмульсией. Выдерживает мойку под давлением. Срок 10+ лет (база A)' },
        { name: 'ULTRA DURABLE (база A)', unit: '9,00 л', price: 8160.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'SILICATE PROFI', unit: '9,00 л', price: 7930.0, coverage: 0, category: 'BAYRAMIX', description: 'Для фасадов. Высокая паропроницаемость. Срок 12+ лет (база A)' },
        { name: 'SILICATE EXTRA', unit: '9,00 л', price: 10170.0, coverage: 0, category: 'BAYRAMIX', description: 'Силикатная + силикон. Грязеотталкивание, паропроницаемость (база A)' },
        { name: 'PRIMER SILICATE', unit: '5 л', price: 3150.0, coverage: 0, category: 'BAYRAMIX', description: 'Грунт-концентрат на силикатной основе' },
        { name: 'PRIMER SILICATE', unit: '10 л', price: 6200.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'КМ0 EXTRA', unit: '9,00 л', price: 7220.0, coverage: 0, category: 'BAYRAMIX', description: 'Краска для путей эвакуации на жидком калиевом стекле. Негорючая. (база A)' },
        { name: 'КМ0 EXTRA (база C)', unit: '9,00 л', price: 7220.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'КМ0 Грунт кварцевый', unit: '6 кг', price: 2340.0, coverage: 0, category: 'BAYRAMIX', description: 'Укрывающий кварцевый грунт КМ0' },
        { name: 'КМ0 Грунт кварцевый', unit: '12 кг', price: 4680.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'КМ0 Грунт глубокого проникновения', unit: '5 кг', price: 1020.0, coverage: 0, category: 'BAYRAMIX', description: 'Грунт для подготовки под негорючие краски' },
        { name: 'КМ0 Грунт глубокого проникновения', unit: '10 кг', price: 1930.0, coverage: 0, category: 'BAYRAMIX', description: '' },
        { name: 'ОПТИМА Роллерная штукатурка', unit: '15 кг', price: 2970.0, coverage: 0, category: 'PRORAB', description: 'Мелкорельефное покрытие. Скрывает дефекты. Колеруется.' },
        { name: 'ROLERDECO XL', unit: '15 кг', price: 3710.0, coverage: 0, category: 'PRORAB', description: 'Толстослойная штукатурка, крупный рельеф. Колеруется.' },
        { name: 'КРАСКА ФАКТУРНАЯ', unit: '15 кг', price: 3130.0, coverage: 0, category: 'PRORAB', description: 'Рельефное покрытие. Наружные и внутренние. Колеруется.' },
        { name: 'МОЮЩАЯСЯ', unit: '9,00 л', price: 3400.0, coverage: 0, category: 'PRORAB', description: 'Интерьерная влагостойкая, матовая (база A)' },
        { name: 'МОЮЩАЯСЯ (база C)', unit: '9,00 л', price: 3070.0, coverage: 0, category: 'PRORAB', description: '' },
        { name: 'ИНТЕРЬЕРНАЯ', unit: '9,00 л', price: 2330.0, coverage: 0, category: 'PRORAB', description: 'Для стен и потолков, укрывистая и экономичная (база A)' },
        { name: 'ИНТЕРЬЕРНАЯ (база C)', unit: '9,00 л', price: 3070.0, coverage: 0, category: 'PRORAB', description: '' },
        { name: 'ФАСАДНАЯ', unit: '9,00 л', price: 3070.0, coverage: 0, category: 'PRORAB', description: 'Для минеральных оснований (база A)' },
        { name: 'ФАСАДНАЯ (база C)', unit: '9,00 л', price: 3070.0, coverage: 0, category: 'PRORAB', description: '' },
        { name: 'ОПТИМА для СТЕН и ПОТОЛКОВ', unit: '14 кг', price: 1800.0, coverage: 0, category: 'PRORAB', description: 'Экономичная, простая в применении (база A)' },
        { name: 'ОПТИМА ФАСАДНАЯ (база A)', unit: '14 кг', price: 2330.0, coverage: 0, category: 'PRORAB', description: '' },
        { name: 'УКРЫВАЮЩИЙ', unit: '16 кг', price: 2810.0, coverage: 0, category: 'PRORAB', description: 'Акриловый грунт с кварц. наполнителем для декоративной отделки' },
        { name: 'Глубокого Проникновения', unit: '10 л', price: 910.0, coverage: 0, category: 'PRORAB', description: 'Водно-дисп. грунт для наружных и внутренних работ' },
        { name: 'ОПТИМА Глубокого Проникновения', unit: '10 л', price: 750.0, coverage: 0, category: 'PRORAB', description: 'Укрепляющий грунт на акриловой основе' },
        { name: 'Шпатель 60 мм сталь Inox', unit: '501/IS-060', price: 1970.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Шпатель 80 мм сталь Inox', unit: '501/IS-080', price: 2080.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Шпатель 100 мм сталь Inox', unit: '501/IS-100', price: 2380.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Шпатель 120 мм сталь Inox', unit: '501/IS-120', price: 2680.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кельма 200×80 мм белый пластик', unit: '817/PV-1', price: 1330.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кельма 240×100 мм сталь Inox', unit: '824/I-2', price: 8320.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кельма Domo 200×80 мм сталь Inox', unit: '894/I-080', price: 4160.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кельма Domo 240×100 мм сталь Inox', unit: '894/I-100', price: 4360.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кельма «Золото Венеции» 200×80 мм сталь Inox', unit: '844/I-1', price: 7910.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Шпатель японский набор (50/80/100/120 мм) Inox', unit: '59415', price: 1000.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Губка абразивная для углов 100 мк', unit: '59526', price: 330.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кисть-флейц Sensitive 40 мм', unit: '59046', price: 810.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кисть-флейц Sensitive 50 мм', unit: '59047', price: 900.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кисть-флейц Sensitive 60 мм', unit: '59048', price: 1020.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кисть-флейц Sensitive 75 мм', unit: '59049', price: 1170.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кисть-флейц Sensitive 100 мм', unit: '59050', price: 1420.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кисть-флейц Forest 60 мм', unit: '59056', price: 1010.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кисть-флейц Forest 100 мм', unit: '59057', price: 1390.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кисть-флейц Cheap & Chic 25 мм', unit: '59005', price: 290.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кисть-флейц Cheap & Chic 40 мм', unit: '59006', price: 330.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кисть-флейц Cheap & Chic 50 мм', unit: '59007', price: 380.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кисть-флейц Cheap & Chic 60 мм', unit: '59008', price: 470.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кисть-флейц Cheap & Chic 75 мм', unit: '59009', price: 730.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кисть-флейц Cheap & Chic 100 мм', unit: '59010', price: 870.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Валик «Длинный ворс Super» 22 см полиамид 19 мм', unit: '59120', price: 1360.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Станок-бюгель 22 см Ø8 мм (алюминий)', unit: '59130', price: 820.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Станок-бюгель 22 см Ø8 мм (сталь)', unit: '59131', price: 660.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кельма ABS закруглённая 200×80 мм', unit: '13122', price: 1270.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кельма ABS волнообразная 200×80 мм', unit: '13123', price: 1250.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кельма Flex Premium 280×120 мм сталь', unit: '13102', price: 5020.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кельма 200×80 мм сталь Inox', unit: '07997', price: 2760.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кельма 240×100 мм сталь Inox', unit: '07996', price: 2880.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кисть скошенная 40 мм', unit: '97840', price: 750.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Кисть Макловица 150 мм', unit: '92715', price: 2730.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Аппликатор 15 см резина', unit: '09587', price: 2570.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Валик для шпатлёвки 22 см Ø50 в сборе', unit: '07352', price: 2330.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Удлинитель 2 м алюминий', unit: '07699', price: 1760.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Удлинитель телескоп. 1,3 м пластик', unit: '13273', price: 540.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Лента малярная розовая деликатная 24 мм×45 м', unit: '08298', price: 1120.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Лента малярная 48 мм×45 м крепированная', unit: '08264', price: 650.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Губка абразивная для углов 100 мк', unit: '09069', price: 330.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Клинер-расческа для всех типов валиков, Inox', unit: '13036', price: 1560.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Щётка обойная 31 см пластик', unit: '13278', price: 1140.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'Защитная плёнка PENTRILO 4×5 м плотная', unit: '08112', price: 1000.0, coverage: 0, category: 'Инструменты', description: '' },
        { name: 'ECOTINT HC B-FT Violet', unit: '1 л', price: 2070.0, coverage: 0, category: 'ECOTINT', description: 'Фиолетовый' },
        { name: 'ECOTINT HC B-HS Bordeaux', unit: '1 л', price: 4320.0, coverage: 0, category: 'ECOTINT', description: 'Бордо' },
        { name: 'ECOTINT HC B-KS Yellow', unit: '1 л', price: 2610.0, coverage: 0, category: 'ECOTINT', description: 'Жёлтый' },
        { name: 'ECOTINT HC B-LS Green Strong', unit: '1 л', price: 2360.0, coverage: 0, category: 'ECOTINT', description: 'Зелёный насыщенный' },
        { name: 'ECOTINT HC B-LT Green', unit: '1 л', price: 2390.0, coverage: 0, category: 'ECOTINT', description: 'Зелёный' },
        { name: 'ECOTINT HC B-MS Blue Strong', unit: '1 л', price: 2630.0, coverage: 0, category: 'ECOTINT', description: 'Синий насыщенный' },
        { name: 'ECOTINT HC B-MT Blue', unit: '1 л', price: 1430.0, coverage: 0, category: 'ECOTINT', description: 'Синий' },
        { name: 'ECOTINT HC B-PT Orange Red', unit: '1 л', price: 6640.0, coverage: 0, category: 'ECOTINT', description: 'Оранжево-красный' },
        { name: 'ECOTINT HC B-RS Red', unit: '1 л', price: 3160.0, coverage: 0, category: 'ECOTINT', description: 'Красный' },
        { name: 'ECOTINT HC B-RT Yellow Oxide', unit: '1 л', price: 1760.0, coverage: 0, category: 'ECOTINT', description: 'Оксид железа жёлтый' },
        { name: 'ECOTINT HC B-ST Umber', unit: '1 л', price: 1490.0, coverage: 0, category: 'ECOTINT', description: 'Умбра' },
        { name: 'ECOTINT HC B-TT Black', unit: '1 л', price: 1380.0, coverage: 0, category: 'ECOTINT', description: 'Чёрный' },
        { name: 'ECOTINT HC B-US Orange Yellow', unit: '1 л', price: 5820.0, coverage: 0, category: 'ECOTINT', description: 'Оранжево-жёлтый' },
        { name: 'ECOTINT HC B-VT Red Oxide', unit: '1 л', price: 2030.0, coverage: 0, category: 'ECOTINT', description: 'Оксид железа красный' },
        { name: 'ECOTINT HC B-XT White', unit: '1 л', price: 2430.0, coverage: 0, category: 'ECOTINT', description: 'Белый' },
        { name: 'ECOTINT HC B-ZT Yellow', unit: '1 л', price: 4490.0, coverage: 0, category: 'ECOTINT', description: 'Жёлтый интенсивный' },
        // Декоративные штукатурки с нормой расхода (для калькулятора)
        { name: 'DECORAZZA Stucco Veneziano', unit: 'кг', price: 980, coverage: 0.35, category: 'Штукатурки', description: 'Венецианская штукатурка, эффект полированного мрамора' },
        { name: 'DECORAZZA Art Beton', unit: 'кг', price: 720, coverage: 0.8, category: 'Штукатурки', description: 'Эффект декоративного бетона, стиль лофт' },
        { name: 'DECORAZZA Travertino Naturale', unit: 'кг', price: 540, coverage: 1.2, category: 'Штукатурки', description: 'Имитация натурального травертина' },
        { name: 'DECORAZZA Romano', unit: 'кг', price: 420, coverage: 2.5, category: 'Штукатурки', description: 'Фактурная штукатурка для фасадов и интерьеров' },
        { name: 'DECORAZZA Rustic', unit: 'кг', price: 380, coverage: 3.0, category: 'Штукатурки', description: 'Грубая фактура, вид натурального камня' },
        { name: 'DECORAZZA Barilievo', unit: 'кг', price: 580, coverage: 1.8, category: 'Штукатурки', description: 'Рельефная штукатурка с объёмными узорами' },
        { name: 'BAYRAMIX Mineral', unit: 'кг', price: 220, coverage: 3.2, category: 'Штукатурки', description: 'Минеральная фасадная штукатурка' },
        { name: 'BAYRAMIX Baytera (Короед)', unit: 'кг', price: 260, coverage: 3.5, category: 'Штукатурки', description: 'Фактурная штукатурка типа короед' },
        { name: 'BAYRAMIX Gravol (Камешковая)', unit: 'кг', price: 240, coverage: 2.8, category: 'Штукатурки', description: 'Зернистая штукатурка, тип камешковая' },
        { name: 'Грунтовка адгезионная', unit: 'л', price: 180, coverage: 6.0, category: 'Штукатурки', description: 'Под декоративные штукатурки' },
        { name: 'Воск защитный прозрачный', unit: 'л', price: 420, coverage: 8.0, category: 'Штукатурки', description: 'Финишная защита поверхности' },
]

async function seedIfEmpty() {
  await db.transaction('rw', db.products, db.laborRates, db.settings, async () => {
    const productCount = await db.products.count()
    if (productCount === 0) {
      await db.products.bulkAdd(CATALOG_PRODUCTS as Product[])
    }

    const laborCount = await db.laborRates.count()
    if (laborCount === 0) {
      await db.laborRates.bulkAdd([
        { name: 'Подготовка поверхности (шпаклёвка)', pricePerSqm: 250, unit: 'м²' },
        { name: 'Нанесение грунтовки', pricePerSqm: 80, unit: 'м²' },
        { name: 'Нанесение декоративной штукатурки', pricePerSqm: 450, unit: 'м²' },
        { name: 'Венецианская штукатурка (2–3 слоя)', pricePerSqm: 1200, unit: 'м²' },
        { name: 'Покрытие воском/лаком', pricePerSqm: 150, unit: 'м²' },
      ])
    }

    const settingsCount = await db.settings.count()
    if (settingsCount === 0) {
      await db.settings.add({
        name: 'ООО "АКЦЕНТ"',
        address: '',
        phone: '',
        inn: '7814860953',
        kpp: '781401001',
        ogrn: '1267800014206',
        logo: '',
        bankName: 'СЕВЕРО-ЗАПАДНЫЙ БАНК ПАО СБЕРБАНК',
        bankBik: '044030653',
        bankAccount: '40702810555710020199',
        bankCorrAccount: '30101810500000000653',
        bankInn: '7707083893',
        bankKpp: '784243001',
        adText: 'Барельефы · Скалы · Травертин · Шёлк и другие декоративки · Обучение и мастер-классы',
      })
    }
  })
}

seedIfEmpty().catch(console.error)
